#!/bin/sh
test "$TRACE" && set -x
test "$TRACE" && export LIBGUESTFS_DEBUG=1
test "$TRACE" && export LIBGUESTFS_TRACE=1

TOOL=$(basename "$0")

cat <<'dockerfile' | sed -e "s#@TOOL@#$TOOL#g" | docker build -t $TOOL - >/dev/null 2>&1
from debian:sid
run  export DEBIAN_FRONTEND=noninteractive \
&&   apt update \
&&   apt install -y libguestfs-tools \
&&   apt-get clean
env  LIBGUESTFS_BACKEND=direct
env  LIBGUESTFS_HV=/usr/bin/qemu-docker
run  { \
	echo '#!/bin/bash -'; \
	echo 'i=0'; \
	echo 'while [ $# -gt 0 ]; do'; \
	echo 'case "$1" in'; \
	echo '-machine|-cpu)'; \
	echo 'shift 2;;'; \
	echo '*)'; \
	echo 'args[i]="$1"'; \
	echo '(( i++ ))'; \
	echo 'shift ;;'; \
	echo 'esac'; \
	echo 'done'; \
	echo 'exec qemu-system-x86_64 -machine pc,accel=tcg "${args[@]}"'; \
	} | install -m 0755 /dev/stdin $LIBGUESTFS_HV
entrypoint ["@TOOL@"]
dockerfile

exec docker run --rm --env=LIBGUESTFS_DEBUG --env=LIBGUESTFS_TRACE --volume=${BOOT:-/boot}:/boot:ro --volume=/lib/modules:/lib/modules:ro --workdir=$PWD --volume=$PWD:$PWD $(test -t 0 && echo "--tty ") --interactive $TOOL "$@"